# General instructions for the AI labeler
instructions: |
  Label issues and pull requests based on their content. Consider the title, 
  description, and any comments when making your decision. For bug reports, 
  carefully check if the issue describes actual broken functionality versus a 
  feature request or question.

# If false, only labels defined here can be used. Default: true
include_repo_labels: false

# Define and customize labels.
labels:
  - abc
  - bug:
    description: "Issues that describe broken functionality"
    instructions: |
      Apply this label when the issue clearly describes unexpected behavior or 
      broken functionality. Look for specific error messages, steps to reproduce, 
      and expected vs actual behavior.

  - enhancement:
    description: "Feature requests and improvements"
    instructions: |
      Use this for suggestions of new features or improvements to existing ones. 
      Should describe what new capability is desired and why it would be useful.

  - documentation:
    description: "Documentation-related issues"
    instructions: |
      Apply to PRs that primarily modify documentation, or issues requesting 
      documentation improvements.

  - question:
    description: "Questions about usage or implementation"
    instructions: |
      For issues that are primarily asking how to use the project or seeking 
      clarification about functionality.

# Additional context files to help with labeling decisions
context_files:
  - .github/CODEOWNERS
  - CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE/bug_report.md
