name: "AI Labeler"
description: "Automatically label PRs and issues using AI"
author: "Jeremiah Lowin"

inputs:
  controlflow-llm-model:
    description: "ControlFlow model to use for AI labeling. Should be openai/<model-name> or anthropic/<model-name>, with the appropriate API key set."
    required: true
    default: "openai/gpt-4o-mini"
  openai-api-key:
    description: "OpenAI API key for AI processing"
    required: false
  anthropic-api-key:
    description: "Anthropic API key for AI processing"
    required: false
  github-token:
    description: "GitHub token with repository access"
    required: true
    default: ${{ github.token}}
  config-path:
    description: "Path to AI Labeler configuration file"
    required: false
    default: ".github/ai-labeler.yml"
  dry-run:
    description: 'If "true", will only suggest labels without applying them'
    required: false
    default: "false"
  event-number:
    description: "PR or Issue number"
    required: false

outputs:
  labels:
    description: "JSON array of labels that were applied"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    OPENAI_API_KEY: ${{ inputs.openai-api-key }}
    ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
    CONTROLFLOW_LLM_MODEL: ${{ inputs.controlflow-llm-model }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
