name: Label issues and PRs with AI

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: AI Labeler
        uses: ./
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
